require "hoangat.core.options"
require "hoangat.core.nvchad"
require "hoangat.core.keymaps"
require "hoangat.core.utils"
require "hoangat.modules.plugins"
require "hoangat.core.autocmd"
require "hoangat.core.compiler"
