#!/bin/sh
# alias j='z'
# alias f='zi'

alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
alias nvimrc='nvim ~/.config/nvim/'
# alias nvim='~/nvim.appimage'
alias vim='~/nvim.appimage'
alias v='~/nvim.appimage'
# alias vim='nvim'
# alias v='nvim'
alias ta='tmux attach'

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

# git
alias m="git checkout master"
alias s="git checkout stable"
alias lg='lazygit'
alias g='git'

# docker
alias d='docker'
alias dsa='docker stop $(docker ps -a -q)'

# Better 'ls'
alias ls='ls -p -G'
alias la='ls -A'
alias ll='exa -l -g --icons'
alias lla='exa -l -g -a --icons'

# case "$(uname -s)" in
#
# Darwin)
# 	# echo 'Mac OS X'
# 	alias ls='ls -G'
# 	;;
#
# Linux)
# 	alias ls='ls --color=auto'
# 	;;
#
# CYGWIN* | MINGW32* | MSYS* | MINGW*)
# 	# echo 'MS Windows'
# 	;;
# *)
# 	# echo 'Other OS'
# 	;;
# esac
